---
- name: Ensure apt cache is up to date.
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Checking if base_path exists
  become: true
  stat:
    path: "{{ base_path }}/"
  register: base_path_check

- name: Create base_path directory
  become: true
  file:
    path: "{{ base_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  when: base_path_check.stat.exists == False

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Ensure pip dependencies are installed
  pip:
    name: pexpect
